# Generated by Django 2.2.12 on 2020-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
