# Generated by Django 2.2.12 on 2020-04-13 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200413_0705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
