# Generated by Django 2.2.12 on 2020-04-13 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0007_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Mobile', models.IntegerField()),
                ('Username', models.CharField(max_length=100)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
